### ISSUE TITLE
modify `consignment_endpoints` parameter

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/invoices#2]
Looking at the `Invoice` struct I see a [`consignment_endpoints` parameter](https://github.com/LNP-BP/invoices/blob/master/rust/src/base.rs#L126) that is defined as `Vec<NodeAddr>`. `NodeAddr` is a struct with an `id` (`NodeId`) and an `addr` (`InetSocketAddr`) and is documented as `Internet P2P node address`.

We believe that `consignment_endpoints` should be changed to something as (wording can be discussed) `Vec<ConsignmentEndpoint>` where `ConsignmentEndpoint` is defined as an enum that can be `Storm(NodeAddr)` or `RestProxy(Url)`. In this way in the future it will be easy and backwards-compatible to add other "protocols" that allow the transfer of consignments.

[rgb-proxy-server](https://github.com/grunch/rgb-proxy-server) is an example of such "rest proxy", I plan to add documentation on "protocol" APIs so that the proxy can be implemented also in other programming languages.

**Comment by dr-orlovsky** [comment]
So you mean that we need to add information about the protocol used by the endpoint providing the service and support endpoints using different protocols? But I am afraid that there is no defined protocol for a `RestPRoxy` - or the one has to be created before adding it.

**Comment by zoedberg** [comment]
It would not be the first thing we implement without having defined a protocol or proper documentation first. I agree we'll need to document it and, as I was saying, I can take care of that, but I think implementation and documentation can go in parallel in this phase of the SW ecosystem. 

I'll open a PR for such change and also a discussion to define details of the rest protocol with the community

**Comment by dr-orlovsky** [comment]
I mean that is no such thing as REST API. There could be thousands or more incompatible REST API and just adding a single enum variant covering all of them would simply not work.

**Comment by zoedberg** [comment]
Not sure what's the issue here. Probably I misused wording, let's call it "RgbJSONProxy" for now and let's discuss naming later. I think that the invoice library should document that for "RgbJSONProxy" we consider all software implementing a protocol that we'll define and llnk in the invoice library (it could be something similar to https://electrum.readthedocs.io/en/latest/protocol.html). In the future we could also have gRPC servers or whatever, in any case the invoices library will surely need to specify what each supported enum variant means.

Our main goal is to improve resilience and usability of the invoice protocol. To achieve that, we believe it should support more than one medium for data exchange. This also allows using it without necessarily relying only on Storm

**Comment by dr-orlovsky** [comment]
I mean that if you have a specific protocol defined in some code (I assume you use gRPC/protobuf, thus you have a protocol definition file) it should be used explicitly. We can add that option, but the protocol should have a name, and reference that specific definition protobuf/gRPC file.

**Comment by zoedberg** [comment]
Some protocols, like gRPC, can define themselves via code, others are defined via documentation. I agree the first way is better, but this doesn't mean we shouldn't also support other types of protocols. The project I've linked (which is the proxy server we are currently using in rgb-lib) is not using gRPC, it's using simple JSON APIs. As a start we want the invoice protocol to support that, then in the future I hope it will support many other data exchange protocols. I'll open a PR and start documenting the protocol so that it will be easier to understand what I mean

**Comment by dr-orlovsky** [comment]
It is not possible to support something which is not defined. We can't support "any REST API" for sending consignments. We must have a list of defined APIs we support - either in docs, protobuf files or both.

**Comment by dr-orlovsky** [comment]
... or at least as a names of specific "REST API protcols" - like "BitfinexRESTApi". Just reserve the name for the API protocol you use and we stick it into the enum (and yes, it has to be `non_exhaustive`)

**Comment by fedsten** [comment]
"BitfinexRESTApi" wouldn't be appropriate as the first implementation of a rest [proxy server for RGB](https://github.com/grunch/rgb-proxy-server) wasn't even made by a Bitfinex affiliated person (@grunch built it). If you didn't intend to reserve the same name for some else, I think `RgbJsonRpc` would be more inclusive.

**Comment by dr-orlovsky** [comment]
I fine with any name as long as it has some reference implementation/spec/api description attached. I mean we can't call it "API" or "REST API", but for sure we can call it `RgbJsonRpc` or anyhow else with a proper/specific (i.e. non-generic) name.
